name: CI

on: [push, pull_request]

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      # Download the code from the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Define .NET enviorment 
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore ./backend/ExpoConnect.sln

      # Build
      - name: Build
        run: dotnet build --no-restore ./backend/ExpoConnect.sln
